apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-listener-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eth-listener
  template:
    metadata:
      labels:
        app: eth-listener
    spec:
      serviceAccountName: gcs-writer-sa
      containers:
      - name: eth-listener
        image: gcr.io/blockchain-analysis-pipeline/eth_listener:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80