apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: eth-block-details
  labels:
    strimzi.io/cluster: kafka-service-cluster
  namespace: kafka
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: eth-block-number
  labels:
    strimzi.io/cluster: kafka-service-cluster
  namespace: kafka
spec:
  partitions: 1
  replicas: 1

# Use the code below to create multiple kafka topics
# ---
# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaTopic
# metadata:
#   name: topic2
#   labels:
#     strimzi.io/cluster: kafka-service-cluster
#   namespace: kafka
# spec:
#   partitions: 3
#   replicas: 3
# ---
# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaTopic
# metadata:
#   name: topic3
#   labels:
#     strimzi.io/cluster: kafka-service-cluster
#   namespace: kafka
# spec:
#   partitions: 3
#   replicas: 3
