apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-application
  template:
    metadata:
      labels:
        app: dummy-application
    spec:
      containers:
      - name: dummy-application
        image: gcr.io/blockchain-analysis-pipeline/dummy-application:v2