apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-test-consumer-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-test-consumer-application
  template:
    metadata:
      labels:
        app: kafka-test-consumer-application
    spec:
      containers:
      - name: kafka-test-consumer-application
        image: gcr.io/blockchain-analysis-pipeline/kafka-test-consumer-application:v1