apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-streamer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-streamer-app
  template:
    metadata:
      labels:
        app: spark-streamer-app
    spec:
      containers:
      - name: spark-streamer-app
        image: gcr.io/blockchain-analysis-pipeline/spark-streamer-app:v1
        imagePullPolicy: Always
